#!/usr/bin/ruby
require 'optparse'
require 'socket'
require 'timeout'
require 'json'
require 'openssl'
require 'base64'

Signal.trap('INT')  { exit 0 } # Trap ^C      == "INT"
Signal.trap('TERM') { exit 0 } # Trap `Kill ` == "TERM"

DEBUG = false
EXIT_CODE  = 255
PROTOCOL_EXIT_CODE = 63
DEVICE_KEY = OpenSSL::Cipher::AES128.new(:CBC).random_key

def generate_hash(value)
    OpenSSL::HMAC.hexdigest(
        OpenSSL::Digest.new('sha256'),
        $secret_key,
        value
    ).strip()
end

def debug(msg)
  puts msg if DEBUG
end

def encrypt(plain_text)
	cipher = OpenSSL::Cipher::AES128.new(:CBC)
	cipher.encrypt
	cipher.key = $secret_key
	cipher.update(plain_text) + cipher.final
end

def decrypt(cipher_text)
	cipher = OpenSSL::Cipher::AES128.new(:CBC)
	cipher.decrypt
	cipher.key = $secret_key
	cipher.update(cipher_text) + cipher.final 
end

def sign(text)
    OpenSSL::HMAC.hexdigest(
        OpenSSL::Digest.new('sha256'),
        DEVICE_KEY,
        text
    ).strip()
end

# All other errors, specified throughout this document or
# unrecoverable errors not explicitly discussed, should prompt the
# program to exit with return code 255

# Numeric inputs are positive and provided in decimal without any
# leading 0's (should match /(0|[1-9][0-9]*)/). Thus "42" is a valid
# input number but the octal "052" or hexadecimal "0x2a" are not.
# Any reference to "number" below refers to this input specification.

def is_valid_balance?(balance, silent=0)
    # Balances and currency amounts are specified as a number
    # indicating a whole amount and a fractional input separated
    # by a period. The fractional input is in decimal and is always
    # two digits and thus can include a leading 0 (should match /[0-9]{2}/).
    # The interpretation of the fractional amount v is that of having
    # value equal to v/100 of a whole amount (akin to cents and dollars in
    # US currency). Balances are bounded from 0.00 to 4294967295.99.
    if balance =~ /^(\d{1,10}).(\d{2})$/
      left_part = balance.split(".")[0]
      if left_part == "0" || left_part[0] != "0"
        balance = balance.to_f
        if balance >= 0.0 && balance <= 4294967295.99
            return true
        end
      end
    end

    debug "Invalid balance: #{balance}" unless silent
    false
end

def is_valid_amount?(amount)
    # Uses the same validation as is_valid_balance?
    result = is_valid_balance?(amount, 1)
    debug "Invalid amount: #{amount}" unless result 

    return result
end

def is_valid_account?(account)
  if account.length >= 1 \
    && account.length <= 250 \
    && account =~ /\A[a-z0-9_\-\.]+\Z/
      return true
  end

  debug "Invalid account: #{account}"
  false
end

def is_valid_ip?(ip)
  if ip =~ /^(\d{1,3}).(\d{1,3}).(\d{1,3}).(\d{1,3})$/
    return true
  end

  debug "Invalid ip #{ip}"
  false
end

def is_valid_port?(port)
  # Length check
  if port.length > 4096
    debug "Invalid length for port (>4096)"
    return false
  end

  # p==0 means invalid integer
  # p<1024 and p>65535 are invalid
  p = port.to_i
  if p!=0 && p >= 1024 && p <= 65535
    return true
  end
  
  debug "Invalid port: #{p}"
  false
end

def is_valid_auth_file?(auth_file, silent=0)
  if ![".",".."].include?(auth_file) \
    && auth_file.length >= 1 \
    && auth_file.length <= 255 \
    && auth_file =~ /\A[a-z0-9_\-\.]+\Z/
      return true
  end

  debug "Invalid auth file: #{auth_file}" unless silent
  false
end

def is_valid_card_file?(card_file)
  result = is_valid_auth_file?(card_file, 1)

  debug "Invalid card_file: #{card_file}" unless result 
  return result
end

def is_valid_atm_time?(atm_time)
  if atm_time.length >= 1 \
    && atm_time.length <= 255 \
    && atm_time =~ /\A[a-z0-9_\-\.]+\Z/
      return true
  end

  debug "Invalid atm_time: #{atm_time}"
  false
end

def are_valid_args?(args, auth_file)
  # ATM time
  if !args[:atm_time] || !is_valid_atm_time?(args[:atm_time])
    debug "are_valid_args? invalid atm time"
    return false
  end

  # Account Name
  if !args[:account] || !is_valid_account?(args[:account])
    debug "are_valid_args? invalid account"
    return false
  end

  # Card File
  if !args[:card_file] || !is_valid_card_file?(args[:card_file])
    debug "are_valid_args? invalid card file"
    return false
  end

  # Auth File
  if !args[:auth_file] || !is_valid_auth_file?(args[:auth_file]) || args[:auth_file]!=auth_file
    debug "are_valid_args? invalid auth file"
    return false
  end

  # Operations
  if !args[:operation] || !["-n","-d","-w","-g"].include?(args[:operation])
    debug "are_valid_args? invalid operation"
    return false
  end

  # -n
  if args[:operation] == "-n" && !is_valid_balance?(args[:operation_value])
    debug "are_valid_args? invalid balance for -n operation"
    return false
  end

  # -d, -w
  if ["-d","-w"].include?(args[:operation]) && !is_valid_amount?(args[:operation_value])
    debug "are_valid_args? invalid amount for operations -d or -w"
    return false
  end

  return true
end

#
# atm is a client program that simulates an ATM by providing
# a mechanism for customers to interact with their bank accounts
# stored on the bank server. atm allows customers to 
# - create new accounts,
# - deposit money,
# - withdraw funds, and
# - check their balances.
# 
# In all cases, these functions are achieved via communiations with
# the bank. atm cannot store any state or write to any files except
# the card-file. The card-file can be viewed as the "pin code" for
# one's account; there is one card file per account.
# 
# Card files are created when atm is invoked with -n to create a new
# account; otherwise, card files are only read, and not modified.
#
# Any invocation of the atm which does not follow the four enumerated
# possibilities above should exit with return code 255 (printing nothing).
# Noncompliance includes a missing account or mode of operation and
# duplicated parameters. Note that parameters may be specified in any order.

options = {}
optparse = OptionParser.new do |opts|
  opts.banner = "Usage: atm -a <account> [-s <auth-file>] [-i <ip-address>] [-p <port>] [-c <card-file>]"
  opts.separator  ""
  opts.separator  "Options"

  # Account
  text = "The customer's account name."
  opts.on("-a <account>","",text) do |input|
    exit(EXIT_CODE) unless is_valid_account?(input)
    options[:account] = input
  end

  # Auth File
  text = "The name of the auth file. If not supplied, defaults to \"bank.auth\""
  opts.on("-s <auth-file>","",text) do |input|
    exit(EXIT_CODE) unless is_valid_auth_file?(input)
    options[:auth_file] = input
  end

  # IP Address
  text = "The IP address that bank is running on. The default value is \"127.0.0.1\"."
  opts.on("-i <ip-address>","",text) do |input|
    exit(EXIT_CODE) unless is_valid_ip?(input)
    options[:ip] = input
  end

  # Port
  text = "The port that bank should listen on. The default is 3000."
  opts.on("-p <port>","",text) do |input|
    exit(EXIT_CODE) unless is_valid_port?(input)
    options[:port] = input
  end

  # Card File
  text = "The customer's atm card file. The default value is the account " \
  "name prepended to \".card\" (\"<account>.card\"). For example, if the " \
  "account name was 55555, the default card file is \"55555.card\"."
  opts.on("-c <card-file>","",text) do |input|
    exit(EXIT_CODE) unless is_valid_card_file?(input)
    options[:card_file] = input
  end

  ##
  # Mode of Operations

  # -n: Create a new account with the given balance.
  text = "Create a new account with the given balance. The account must be" \
  "unique (ie, the account must not already exist). The balance must be " \
  "greater than or equal to 10.00. The given card file must not already " \
  "exist. If any of these conditions do not hold, atm exits with a return" \
  " code of 255. On success, both atm and bank print the account and initial" \
  " balance to standard output, encoded as JSON. The account name is a JSON" \
  " string with key \"account\", and the initial balance is a JSON number with" \
  " key \"initial_balance\" (Example: {\"account\":\"55555\",\"initial_balance\":10.00})." \
  " In addition, atm creates the card file for the new account " \
  "(think of this as like an auto-generated pin)."
  opts.on("-n <balance>","",text) do |input|
    exit(EXIT_CODE) if options[:operation]
    exit(EXIT_CODE) unless is_valid_balance?(input)
    unless input.to_f >= 10.00
      debug "Input lesser than 10"
      exit(EXIT_CODE) 
    end

    options[:operation] = "n"
    options[:operation_value] = input
  end

  # -d: Deposit the amount of money specified
  text = 'Deposit the amount of money specified. The amount must be greater' \
  ' than 0.00. The specified account must exist, and the card file must be' \
  ' associated with the given account (i.e., it must be the same file produced' \
  ' by atm when the account was created). If any of these conditions do not hold,' \
  ' atm exits with a return code of 255. On success, both atm and bank print the' \
  ' account and deposit amount to standard output, encoded as JSON. The account ' \
  'name is a JSON string with key "account", and the deposit amount is a JSON ' \
  'number with key "deposit" (Example: {"account":"55555","deposit":20.00}).'
  opts.on("-d <amount>","",text) do |input|
    exit(EXIT_CODE) if options[:operation]
    exit(EXIT_CODE) unless is_valid_amount?(input)
    unless input.to_f > 0.00
      debug "Input lesser than 0"
      exit(EXIT_CODE) 
    end
    options[:operation] = "d"
    options[:operation_value] = input
  end

  # -w: Withdraw the amount of money specified
  text = 'Withdraw the amount of money specified. The amount must be greater ' \
  'than 0.00, and the remaining balance must be nonnegative. The card file' \
  ' must be associated with the specified account (i.e., it must be the same' \
  ' file produced by atm when the account was created). The ATM exits with a ' \
  'return code of 255 if any of these conditions are not true. On success, ' \
  'both atm and bank print the account and withdraw amount to standard output,' \
  ' encoded as JSON. The account name is a JSON string with key "account", and' \
  ' the withdraw amount is a JSON number with key "withdraw" (Example:'\
  ' {"account":"55555","withdraw":15.00}).'
  opts.on("-w <amount>","",text) do |input|
    exit(EXIT_CODE) if options[:operation]
    exit(EXIT_CODE) unless is_valid_amount?(input)
    unless input.to_f > 0.00
      debug "Input lesser than 0"
      exit(EXIT_CODE) 
    end
    options[:operation] = "w"
    options[:operation_value] = input
  end

  # -g: Get the current balance of the account
  text = 'Get the current balance of the account. The specified account must '\
  'exist, and the card file must be associated with the account. Otherwise, '\
  'atm exits with a return code of 255. On success, both atm and bank print '\
  'the account and balance to stdout, encoded as JSON. The account name is '\
  'a JSON string with key "account", and the balance is a JSON number with '\
  'key "balance" (Example: {"account":"55555","balance":43.63}).'
  opts.on("-g","",text) do |input|
    exit(EXIT_CODE) if options[:operation]
    options[:operation] = "g"
  end

end

begin
  optparse.parse!
rescue
  debug "invalid arguments #{options.inspect}"
  exit(EXIT_CODE)
end

# Check required conditions
unless ARGV.empty?
  debug "Extra parameters"
  exit(EXIT_CODE)
end

# Debug: print received options
debug options.inspect

# Default Parameters Values
account         = options[:account]
operation       = options[:operation]
operation_value = options[:operation_value]
ip              = options[:ip]        || "127.0.0.1"
port            = (options[:port]     || "3000").to_i
auth_file       = options[:auth_file] || "bank.auth"
card_file       = options[:card_file] || "#{options[:account]}.card"


# Mandatory parameters verification
["account", "operation"].each do |var|
    eval(
        <<-VERIFICATION
            unless #{var}
                debug "Not specified argument: #{var}"
                exit(EXIT_CODE)
            end
        VERIFICATION
    )
end

# If the specified file cannot be opened,
# the atm exits with a return code of 255.
unless File.exist?(auth_file)
  debug "File does not exist: #{auth_file}"
  exit(EXIT_CODE)
end

begin
  $secret_key = Base64.decode64(File.open(auth_file, "r").read.split("\n").first)
  debug Base64.encode64($secret_key)
rescue Errno::EACCES
  debug "No permission to open file: #{auth_file}"
  exit(EXIT_CODE)
end

#
# ================= OPERATION SPECIFIC
#

if operation == "n"
  # Create Card File if operation is "-n"
  if File.exist?(card_file)
    debug "Card File exists: #{card_file}"
    exit(EXIT_CODE)
  end

  begin
      File.open(card_file, "w") do |f|
        f << generate_hash(account)
      end
  rescue Errno::ENOENT
    debug "Could not create: #{card_file} | ENOENT"
    exit(EXIT_CODE)
  rescue Errno::EACCES
    debug "Could not create: #{card_file} | EACCES"
    exit(EXIT_CODE)
  end
end

if ["d","w","g"].include?(operation)
  # Check if account/card exists
  unless File.exist?(card_file)
    debug "File not found: #{card_file}"
    exit(EXIT_CODE)
  end

  # Check if has permission to open file
  begin
    f = File.open(card_file,  "r")
  rescue Errno::EACCES
    debug "No permission to open file: #{card_file}"
    exit(EXIT_CODE)
  end

  # Is its size >= 1 MB?
  if (File.size(card_file).to_f / 1024000) >= 1
    debug "Card file too big: #{File.size(card_file).to_f}"
    exit(EXIT_CODE)
  end

  # Read Contents
  card_file_contents = File.open(card_file, "rb").read

  # Check if they match (account/card_file), a.k.a Authentication
  unless card_file_contents == generate_hash(account)
    debug "Invalid account or card file"
    exit(EXIT_CODE)
  end
end

## TCP Communication w/ BANK
# 

begin
  Timeout::timeout(10) do
    Socket.tcp(ip, port) {|sock|
      # A timeout occurs if the other program does not respond
      # within 10 seconds. If the atm observes the timeout, it
      # should exit with return code 63

      input = [
            "-p",
            port.to_s,
            "-i",
            ip,
            "-a",
            account,
            "-c",
            card_file,
            "-s",
            auth_file,
            "-#{operation}"
        ]
      # As -g does not have a value
      # We only add the operation_value if not empty
      input << operation_value if operation_value

      # Time to prevent replay attacks
      input << "atm_time"
      input << generate_hash(Time.now.to_s)

      message = {
        input: input,
        base64: false
      }.to_json

      sock.print Base64.strict_encode64(encrypt(message))
      sock.close_write
      raw_result = sock.read

      begin
        result = JSON.parse(raw_result)
      rescue JSON::ParserError
        debug "json parser error"
        exit(PROTOCOL_EXIT_CODE)
      end

      # Exit when bank announce an error / violation
      if result["error"]
        debug "Exiting as bank said to #{result}"
        exit(EXIT_CODE)
      end

      STDOUT.puts raw_result
      STDOUT.flush
    }
  end
rescue =>e 
    # If an error is detected in the protocol's communication,
    # atm should exit with return code 63, while bank should
    # print "protocol_error" to stdout (followed by a newline)
    # and roll back (i.e., undo any changes made by) the current
    # transaction.

    debug "generic socket rescue: #{e.class}: #{e.message} \nBacktrace #{e.backtrace}"
    exit(PROTOCOL_EXIT_CODE)
end
